
import Database.DatabaseManager;
import java.awt.Container;
import static java.lang.Integer.parseInt;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Raiyan
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeFrame
     */
    public Employee() {

        initComponents();

        //frameColor();
        getEmployee();

        ButtonGroup bg = new ButtonGroup();
        bg.add(male);
        bg.add(female);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employee = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        src = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        hospitalComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Details");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        employee.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Phone", "Email", "Address", "Hospital ID"
            }
        ));
        jScrollPane1.setViewportView(employee);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(264, 134, 828, 450);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Employee Details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 70, 360, 48);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("New Entry");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 98, 108, 27);

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Employee Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(69, 143, 130, 22);

        name.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(name);
        name.setBounds(35, 176, 200, 34);

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Select");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(59, 228, 60, 22);

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(59, 256, 60, 22);

        female.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        getContentPane().add(female);
        female.setBounds(137, 256, 67, 25);

        male.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setSelected(true);
        male.setText("Male");
        getContentPane().add(male);
        male.setBounds(137, 228, 53, 25);

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Contact Number");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(64, 294, 140, 22);

        phone.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(phone);
        phone.setBounds(35, 322, 200, 34);

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(109, 367, 50, 22);

        mail.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(mail);
        mail.setBounds(35, 395, 200, 34);

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Address");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(92, 440, 70, 22);

        address.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(address);
        address.setBounds(35, 468, 200, 34);

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Hospital Name");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(71, 513, 130, 22);

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Search Here");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1158, 317, 132, 27);

        src.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        src.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        src.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcActionPerformed(evt);
            }
        });
        src.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcKeyReleased(evt);
            }
        });
        getContentPane().add(src);
        src.setBounds(1122, 355, 210, 34);

        insert.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert);
        insert.setBounds(71, 606, 130, 53);

        delete.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(621, 607, 130, 50);

        getContentPane().add(hospitalComboBox);
        hospitalComboBox.setBounds(40, 540, 190, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectInnerPicture.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        try {

            setEmployee();
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Data Inserted Successfully!" + ex, "Connection Status", JOptionPane.INFORMATION_MESSAGE);

            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insertActionPerformed

    private void srcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcKeyReleased
        ResultSet rs;
        DatabaseManager employeeData = DatabaseManager.getInstace();
        PreparedStatement pst;
        String search = src.getText();

        try {
            if (search.matches("^[0-9]+$") && search.charAt(0) != '0') {
                String query = "Select * from tbl_employee where employeeId = " + search + " or hospitalID = " + search;
                pst = employeeData.getPreparedStatement(query);
                rs = pst.executeQuery();
                employee.setModel(DbUtils.resultSetToTableModel(rs));
            } else {
                String query = "Select * from tbl_employee where emp_name Like '%" + search + "%' or emp_gender Like '" + search + "%' or emp_address Like '%" + search + "%' or emp_email Like '%" + search + "%' or emp_contact Like '%" + search + "%'";
                pst = employeeData.getPreparedStatement(query);
                rs = pst.executeQuery();
                employee.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please Check Database.Something is Wrong!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_srcKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(1400, 760);
    }//GEN-LAST:event_formWindowOpened

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        int row = employee.getSelectedRow();

        Object index = employee.getValueAt(row, 0);

        try {
            DatabaseManager employeeData = DatabaseManager.getInstace();

            String query = "DELETE FROM tbl_employee Where employeeID = " + index;
            PreparedStatement pst = employeeData.getPreparedStatement(query);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Deleted Successfully!", "Connection Status", JOptionPane.INFORMATION_MESSAGE);

            getEmployee();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Please Check The Connection Settings!\nOr Fill The From Correctly", "Error!", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton delete;
    private javax.swing.JTable employee;
    private javax.swing.JRadioButton female;
    private javax.swing.JComboBox<String> hospitalComboBox;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mail;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField src;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        name.setText("");
        phone.setText("");
        mail.setText("");
        address.setText("");
        male.setSelected(true);
    }

    private void getEmployee() {

        Hospital hospital = new Hospital();
        hospitalComboBox.removeAllItems();
        hospital.setHospitalComboBox(this.hospitalComboBox);

        DefaultTableModel mod = (DefaultTableModel) employee.getModel();
        while (mod.getRowCount() > 0) {
            mod.removeRow(0);
        }

        DatabaseManager employeeData = DatabaseManager.getInstace();
        //System.out.println(patient.checkConnection());

        if (employeeData.checkConnection()) {
            String query = "Select * from tbl_employee";
            ResultSet rset = null;
            try {
                rset = employeeData.getResult(query);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Please Check Database.Something is Wrong!!", "Warning", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                while (rset.next()) {
                    int id = rset.getInt("employeeId");
                    String name = rset.getString("emp_name");
                    String gen = rset.getString("emp_gender");
                    String contact = rset.getString("emp_contact");
                    String email = rset.getString("emp_email");
                    String address = rset.getString("emp_address");
                    String hos = rset.getString("hospitalID");

                    Object[] row = {id, name, gen, contact, email, address, hos};

                    DefaultTableModel model = (DefaultTableModel) employee.getModel();
                    model.addRow(row);

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Please Check Database.Something is Wrong!!", "Warning", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void setEmployee() throws SQLException {

        Hospital hospital = new Hospital();
        String nam = name.getText();
        String ph = phone.getText();
        String email = mail.getText();
        String add = address.getText();
        String hsName = hospitalComboBox.getSelectedItem().toString();
        int hos = hospital.getHospitalID(hsName);

        String gen = null;

        if (male.isSelected()) {
            gen = "male";
        } else if (female.isSelected()) {
            gen = "female";
        }

        if (nam.isEmpty() || ph.isEmpty() || email.isEmpty() || gen.isEmpty() || hsName.isEmpty() || add.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Fill The Entry Form Correctly", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                DatabaseManager employeeData = DatabaseManager.getInstace();

                String query = "INSERT INTO tbl_employee(emp_name,emp_gender,emp_contact,emp_email,emp_address,hospitalId) VALUES(?,?,?,?,?,?)";
                PreparedStatement pst = employeeData.getPreparedStatement(query);

                pst.setString(1, nam);
                pst.setString(2, gen);
                pst.setString(3, ph);
                pst.setString(4, email);
                pst.setString(5, add);
                pst.setInt(6, hos);

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Inserted Successfully!", "Connection Status", JOptionPane.INFORMATION_MESSAGE);

                getEmployee();

                clear();
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Please Check The Connection Settings!\nOr Fill The From Correctly", "Error!", JOptionPane.ERROR_MESSAGE);

            }
        }
    }

    public void setEmployeeComboBox(JComboBox employeeComboBox) {
        DatabaseManager employeeData = DatabaseManager.getInstace();

        if (employeeData.checkConnection()) {
            ResultSet rset = null;
            try {
                String query = "Select * from tbl_employee";
                rset = employeeData.getResult(query);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Please Check Database.Something is Wrong!!", "Warning", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                while (rset.next()) {
                    String hospitalName = rset.getString("emp_name");
                    employeeComboBox.addItem(hospitalName);

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Please Check Database.Something is Wrong!!", "Warning", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public int getEmployeeID(String employeeName) {
        DatabaseManager hospitalData = DatabaseManager.getInstace();
        int employeeID = 0;
        if (hospitalData.checkConnection()) {
            ResultSet rset = null;
            try {
                String query = "Select employeeID from tbl_employee where emp_name = " + "'" + employeeName + "';";
                rset = hospitalData.getResult(query);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Please Check Database.Something is Wrong!!", "Warning", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                while (rset.next()) {
                    employeeID = Integer.parseInt(rset.getString("employeeID"));
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Please Check Database.Something is Wrong!!", "Warning", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return employeeID;

    }

    private void frameColor() {
        Container c;
        JLabel imageLabel;
        ImageIcon img;

        c = this.getContentPane();
        c.setLayout(null);

        img = new ImageIcon(getClass().getResource("img2.jpg"));
        imageLabel = new JLabel(img);
        imageLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
        c.add(imageLabel);

        //Icon Set
        img = new ImageIcon(getClass().getResource("img2.jpg"));
        this.setIconImage(img.getImage());
    }

}
